# Generated by Django 4.0 on 2021-12-19 16:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('exploration_questions', models.IntegerField(default=0)),
                ('feedback_entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_in_games', to='open_20q_api.entity')),
                ('guessed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guessed_in_games', to='open_20q_api.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('yes_count', models.FloatField(default=0)),
                ('no_count', models.FloatField(default=0)),
                ('unknown_count', models.IntegerField(default=0)),
                ('locked_to', models.BooleanField(default=None, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_20q_api.entity')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_20q_api.question')),
            ],
        ),
        migrations.CreateModel(
            name='GameQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entropy', models.FloatField(default=0)),
                ('answer', models.CharField(max_length=10, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_20q_api.game')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_20q_api.question')),
            ],
        ),
        migrations.CreateModel(
            name='GameEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_score', models.FloatField(default=0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_20q_api.entity')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_20q_api.game')),
            ],
        ),
    ]
