# Generated by Django 4.0 on 2021-12-24 00:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('open_20q_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamequestion',
            name='asked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
